@baseUrl = http://localhost:3000
@token = paste-token-from-verify-response

### Health check
# @name health
GET {{baseUrl}}/health

### authentication
# @name login
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "demo@demo.com",
  "password": "demo123"
}

### verify OTP from login challenge
# @name verifyOtpFromLogin
POST {{baseUrl}}/api/v1/auth/otp/verify
Content-Type: application/json

{
  "challengeId": "{{login.response.body.$.challengeId}}",
  "otp": "123456"
}

### get me
# @name me
GET {{baseUrl}}/api/v1/auth/me
Authorization: Bearer {{token}}
