@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlbW9AZGVtby5jb20iLCJyb2xlIjoiYWRtaW4iLCJwZXJtaXNzaW9ucyI6eyJDYW5DcmVhdGVXb3Jrc3BhY2UiOnRydWUsIkNhblZpZXdXb3Jrc3BhY2UiOnRydWUsIkNhbkVkaXRXb3Jrc3BhY2UiOnRydWUsIkNhbkRlbGV0ZVdvcmtzcGFjZSI6dHJ1ZSwiQ2FuQ3JlYXRlUHJvamVjdHMiOnRydWUsIkNhblZpZXdQcm9qZWN0cyI6dHJ1ZSwiQ2FuRWRpdFByb2plY3RzIjp0cnVlLCJDYW5EZWxldGVQcm9qZWN0cyI6dHJ1ZSwiQ2FuTWFuYWdlVXNlcnMiOnRydWV9LCJpYXQiOjE3ODY4MDc5MjYsImV4cCI6MTc4NjgxMTUyNiwic3ViIjoiMSJ9.J1up2dBcTxp3qMdvBfb5dfxT88-RVgo95DrDHh-1sh4

### Health check
GET {{baseUrl}}/health

### authentication
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "demo@demo.com",
  "password": "demo123"
}

### get me
GET {{baseUrl}}/api/v1/auth/me
Authorization: Bearer {{token}}
